<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('menu_items')->delete();
        
        \DB::table('menu_items')->insert(array (
            0 => 
            array (
                'id' => 1,
                'menu_id' => 1,
                'title' => 'Dashboard',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-boat',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 1,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-13 22:31:12',
                'route' => 'voyager.dashboard',
                'parameters' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'menu_id' => 1,
                'title' => 'Media',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-images',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 4,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.media.index',
                'parameters' => NULL,
            ),
            2 => 
            array (
                'id' => 3,
                'menu_id' => 1,
                'title' => 'Users',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 3,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-13 22:31:12',
                'route' => 'voyager.users.index',
                'parameters' => NULL,
            ),
            3 => 
            array (
                'id' => 4,
                'menu_id' => 1,
                'title' => 'Roles',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-lock',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 2,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-13 22:31:12',
                'route' => 'voyager.roles.index',
                'parameters' => NULL,
            ),
            4 => 
            array (
                'id' => 5,
                'menu_id' => 1,
                'title' => 'Tools',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-tools',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 5,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => NULL,
                'parameters' => NULL,
            ),
            5 => 
            array (
                'id' => 6,
                'menu_id' => 1,
                'title' => 'Menu Builder',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-list',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 1,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.menus.index',
                'parameters' => NULL,
            ),
            6 => 
            array (
                'id' => 7,
                'menu_id' => 1,
                'title' => 'Database',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-data',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 2,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.database.index',
                'parameters' => NULL,
            ),
            7 => 
            array (
                'id' => 8,
                'menu_id' => 1,
                'title' => 'Compass',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-compass',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 3,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.compass.index',
                'parameters' => NULL,
            ),
            8 => 
            array (
                'id' => 9,
                'menu_id' => 1,
                'title' => 'BREAD',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-bread',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 4,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.bread.index',
                'parameters' => NULL,
            ),
            9 => 
            array (
                'id' => 10,
                'menu_id' => 1,
                'title' => 'Settings',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-settings',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-08-13 22:31:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.settings.index',
                'parameters' => NULL,
            ),
            10 => 
            array (
                'id' => 14,
                'menu_id' => 1,
                'title' => 'Hooks',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-hook',
                'color' => NULL,
                'parent_id' => 5,
                'order' => 5,
                'created_at' => '2018-08-13 22:31:19',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.hooks',
                'parameters' => NULL,
            ),
            11 => 
            array (
                'id' => 15,
                'menu_id' => 1,
                'title' => 'Actividades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-calendar',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-08-14 17:53:55',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.actividades.index',
                'parameters' => 'null',
            ),
            12 => 
            array (
                'id' => 16,
                'menu_id' => 1,
                'title' => 'Estados Actividades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2018-08-14 17:54:23',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.estados-actividad.index',
                'parameters' => 'null',
            ),
            13 => 
            array (
                'id' => 18,
                'menu_id' => 1,
                'title' => 'Organizador Actividades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-company',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 9,
                'created_at' => '2018-08-14 19:14:20',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.organizador-actividad.index',
                'parameters' => 'null',
            ),
            14 => 
            array (
                'id' => 19,
                'menu_id' => 1,
                'title' => 'Asistentes',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-people',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 10,
                'created_at' => '2018-08-14 19:40:10',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.asistentes.index',
                'parameters' => 'null',
            ),
            15 => 
            array (
                'id' => 20,
                'menu_id' => 1,
                'title' => 'Categoria Actividades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 11,
                'created_at' => '2018-08-14 21:08:12',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.categoria-actividad.index',
                'parameters' => NULL,
            ),
            16 => 
            array (
                'id' => 21,
                'menu_id' => 1,
                'title' => 'Lugares',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-logbook',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 12,
                'created_at' => '2018-08-14 21:08:45',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.lugar.index',
                'parameters' => 'null',
            ),
            17 => 
            array (
                'id' => 22,
                'menu_id' => 1,
                'title' => 'Registrador Actividades',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-person',
                'color' => '#000000',
                'parent_id' => NULL,
                'order' => 13,
                'created_at' => '2018-08-14 21:09:25',
                'updated_at' => '2018-08-14 21:33:08',
                'route' => 'voyager.registrador-actividad.index',
                'parameters' => 'null',
            ),
            18 => 
            array (
                'id' => 23,
                'menu_id' => 1,
                'title' => 'Categories',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-categories',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 8,
                'created_at' => '2018-09-25 03:12:56',
                'updated_at' => '2018-09-25 03:12:56',
                'route' => 'voyager.categories.index',
                'parameters' => NULL,
            ),
            19 => 
            array (
                'id' => 24,
                'menu_id' => 1,
                'title' => 'Posts',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-news',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 6,
                'created_at' => '2018-09-25 03:12:57',
                'updated_at' => '2018-09-25 03:12:57',
                'route' => 'voyager.posts.index',
                'parameters' => NULL,
            ),
            20 => 
            array (
                'id' => 25,
                'menu_id' => 1,
                'title' => 'Pages',
                'url' => '',
                'target' => '_self',
                'icon_class' => 'voyager-file-text',
                'color' => NULL,
                'parent_id' => NULL,
                'order' => 7,
                'created_at' => '2018-09-25 03:12:57',
                'updated_at' => '2018-09-25 03:12:57',
                'route' => 'voyager.pages.index',
                'parameters' => NULL,
            ),
        ));
        
        
    }
}